create table chars (
	id int unsigned not null primary key,
	name varchar(50) not null,
	damage tinyint unsigned not null,
	penalty tinyint(1) not null,
	ability_long_desc varchar(255) not null,
	is_standard tinyint(1) not null,
	kind varchar(100) not null,
	is_tradable tinyint(1) not null,
	pic_url varchar(255) not null,
	power tinyint unsigned not null,
	url varchar(100) not null,
	ability varchar(255) not  null,
	picture_url varchar(255) not null,
	ability_id int unsigned not null,
	bank_price int not null,
	release_date timestamp not null default 0,
	description varchar(255) not null,
	level tinyint not null,
	clan_id int unsigned not null,
	rarity char(1) not null,
	distrib tinyint(1) not null,
	is_valid_elo tinyint(1) not null
) ENGINE=InnoDB DEFAULT CHARSET=utf8 
